---
name: {{ name }}

vcenter:
  address: test
  admin_user: administrator@vsphere.local
  admin_passwd: test
  datacenter: Datacenter
  datastore: Datastore
  cluster: Cluster1

nsxmanager:
  address: 12.1.1.1
  admin_user: user
  admin_passwd: passwd
  #transport_zone: TZ # Specified TransportZone should exist
  transport_zone_clusters: ""
  distributed_portgroup: TestDistributedPortGroup
  enable_dlr: true
  bosh_nsx_enabled: false
  uplink_details:
    primary_ip: 10.114.216.167
    uplink_port_switch: SampleUplinkPort # if not specified, would use VM Networks as default
#  static_routes:
#  - name: static-route-1
#    subnet: 10.0.0.0/8
#    gateway: 10.114.216.180
#    hop: 1

defaults:
  # placeholders, can be comma separated list
  ntp_ips: 1.1.1.1
  dns_ips: 1.1.1.1
  syslog_ips: 1.1.1.1
  ldap_ips: 1.1.1.1

edge_service_gateways:
- name: {{ name }}
  size: compact
  gateway_ip: 10.114.216.1
  cli:
    username: testuser
    password: Test$assword123456
  ospf_password: P!votal #6-8 characters
  ert_certs:
    name: Foundation1
    # cert_id: cert-11 # Uncomment and edit this in order to use an existing cert id
    # # Uncomment and edit below in order to use an existing cert and private key
    # # Ensure the alignment is correct and no extra newlines in either beginning or end of the entry
    # key: |+ # PEM encoded private key 
    #   -----BEGIN RSA PRIVATE KEY-----
    #   MIIEoQIBAAKCAQEAxFT4ktPgj8sBMumiK4nVXGC6UGqXgQkZly/7xC+c5T8pdsvl
    #   ..........................
    #   KdnT9tJIN80VMPkbsNPn2hxx3K7Wbb/tzvRtjCUkqP7/fnVXIQ==
    #   -----END RSA PRIVATE KEY-----
    # cert: |+ # PEM encoded cert 
    #   -----BEGIN CERTIFICATE-----
    #   MIIDwjCCAqqgAwIBAgIJAOx8KRhUILhrMA0GCSqGSIb3DQEBBQUAMEcxJjAkBgNV
    #   ...........
    #   TAvqkR+T
    #   -----END CERTIFICATE-----    
    config:
      org_unit: Pivotal
      country_code: US  # Default - US
      system_domain: pcf-sys-test.corp.local
      app_domain: pcf-app1-test.corp.local,pcf-app2-test.corp.local # comma separated list 
  # iso_certs:
  # - name: Iso1
  #   # cert_id: cert-11 # Uncomment and edit this in order to use an existing cert id
  #   # # Uncomment and edit below in order to use an existing cert and private key
  #   # # Ensure the alignment is correct and no extra newlines in either beginning or end of the entry
  #   # key: |+ # PEM encoded private key 
  #   #   -----BEGIN RSA PRIVATE KEY-----
  #   #   MIIEoQIBAAKCAQEAxFT4ktPgj8sBMumiK4nVXGC6UGqXgQkZly/7xC+c5T8pdsvl
  #   #   ..........................
  #   #   KdnT9tJIN80VMPkbsNPn2hxx3K7Wbb/tzvRtjCUkqP7/fnVXIQ==
  #   #   -----END RSA PRIVATE KEY-----
  #   # cert: |+ # PEM encoded cert 
  #   #   -----BEGIN CERTIFICATE-----
  #   #   MIIDwjCCAqqgAwIBAgIJAOx8KRhUILhrMA0GCSqGSIb3DQEBBQUAMEcxJjAkBgNV
  #   #   ...........
  #   #   TAvqkR+T
  #   #   -----END CERTIFICATE-----    
  #   switch: IsoZone-01 # Should match the logical switch
  #   config:
  #     org_unit: Pivotal
  #     country_code: US  # Default - US
  #     domains: zone1-app.corp.local,zone2-app.corp.local  # comma separated list 
  routed_components:
  - name: opsmgr
    switch: Infra
    external: true
    instances: 1
    offset: 5
    uplink_details:
      uplink_ip: 10.114.216.171 # This gets exposed outside   
    #transport:
      # #Default ingress scheme is https/443 for opsmgr
      # ingress:
      #  port: 443
      #  protocol: https
      # #Default egress scheme is https/443 for opsmgr
      # egress: 
      #  port: 443
      #  protocol: https
      #  monitor_port: 443    
  - name: go-router
    switch: Ert
    external: true
    instances: 4
    offset: 200
    uplink_details:
      uplink_ip: 10.114.216.172 # This gets exposed outside
    #transport:
      # Default ingress scheme is https/443 for ert
      #ingress:
      #  port: 443
      #  protocol: https
      # Default egress scheme is http/8080 for ert
      #egress: 
      #  port: 80
      #  protocol: tcp
      #  monitor_port: 80      
  - name: go-router-nossl
    switch: Ert
    external: true
    instances: 4
    offset: 250
    uplink_details:
      uplink_ip: 10.114.216.173 # This gets exposed outside
    #transport:
      # Default ingress scheme is https/80 for ert
      #ingress:
      #  port: 80
      #  protocol: http
      # Default egress scheme is http/80 for ert
      #egress: 
      #  port: 80
      #  protocol: tcp
      #  monitor_port: 80      

  - name: diego-brain
    switch: Ert
    external: true
    instances: 3
    offset: 180
    uplink_details:
      uplink_ip: 10.193.99.174 # This gets exposed outside  
    #transport:
      #ingress:
      #  port: 2222
      #  protocol: tcp
      #egress: 
      #  port: 2222
      #  protocol: tcp
  - name: tcp-router
    switch: Ert
    external: true
    instances: 4
    offset: 300
    uplink_details:
      uplink_ip: 10.193.99.175 # This gets exposed outside
    #transport:
      # Use defaults - tcp/5000 ingress, tcp/5000 egress
      #ingress:
      #  port: 5000
      #  protocol: tcp
      #egress: 
      #  port: 5000
      #  protocol: tcp
      #  monitor_port: 80
  - name: mysql-ert # Internal ERT MySQL proxy
    switch: Ert
    external: false
    instances: 3
    offset: 100
    uplink_details:
      uplink_ip: 192.168.23.250 # This should be on the Ert network, not external facing
    # transport:
    #   # Use defaults - tcp/3306 incoming, tcp/3306 forward
    #   ingress:
    #     port: 3306
    #     protocol: tcp
    #   egress: 
    #     port: 3306
    #     protocol: tcp
    #     monitor_port: 1936

# Comment off if mysql and rabbitmq not needed
  - name: mysql-tile # MySQL Tile's proxy
    switch: PCF-Tiles
    external: false
    instances: 3 # for 3 proxies in 3 AZs
    offset: 150
    uplink_details:
      uplink_ip: 192.168.27.250 # This should be on the PCF-Tiles network, not external facing
    transport:
      # Use defaults - tcp/3306 incoming, tcp/3306 forward
      ingress:
        port: 3306
        protocol: tcp
      egress: 
        port: 3306
        protocol: tcp
        monitor_port: 1936

  - name: rabbitmq-tile # RabbitMQ Tile's proxy
    switch: PCF-Tiles
    external: false
    instances: 3
    offset: 200
    uplink_details:
      uplink_ip: 192.168.27.251 # This should be on the PCF-Tiles network, not external facing
    transport:
      # Use defaults - tcp/15672,5671,5672 incoming, tcp/15672,5671,5672 forward
      ingress:
        port: 15672,5671,5672
        protocol: tcp
      egress: 
        port: 15672,5671,5672
        protocol: tcp

#  - name: go-router-isozone-1
#    switch: IsoZone-1
#    external: true
#    instances: 2
#    offset: 10
#    uplink_details:
#      uplink_ip: 10.193.99.175 # This gets exposed outside
    #transport:
      # Default ingress scheme is https/443 for ert
      #ingress:
      #  port: 443
      #  protocol: https
      # Default egress scheme is http/8080 for ert
      #egress: 
      #  port: 80
      #  protocol: http
      #  monitor_port: 80
#  - name: tcp-router-isozone-1
#    switch: IsoZone-1
#    external: true
#    instances: 2
#    offset: 30
#    uplink_details:
#      uplink_ip: 10.193.99.176 # This gets exposed outside
    #transport:
      # Use defaults - tcp/5000 ingress, tcp/5000 egress
      #ingress:
      #  port: 5000
      #  protocol: tcp
      #egress: 
      #  port: 5000
      #  protocol: tcp
      #  monitor_port: 80
  # - name: go-router-isozone-2
  #   switch: IsoZone-2
  #   external: true
  #   instances: 2
  #   offset: 10
  #   uplink_details:
  #     uplink_ip: 10.193.99.177 # This gets exposed outside
  #   #transport:
  #     # Default ingress scheme is https/443 for ert
  #     #ingress:
  #     #  port: 443
  #     #  protocol: https
  #     # Default egress scheme is http/8080 for ert
  #     #egress: 
  #     #  port: 80
  #     #  protocol: tcp
  #     #  monitor_port: 80
  
  ## Sample service entry
  # - name: test-service
  #   switch: PCF-Tiles
  #   external: true
  #   instances: 4
  #   offset: 30
  #   uplink_details:
  #     uplink_ip: 10.193.99.41
  #   transport:
  #     #Use defaults - https/443 incoming, http/80 forward
  #     ingress:
  #       port: 443
  #       protocol: https
  #     egress:
  #       port: 80
  #       protocol: http

logical_switches:
- name: OSPF  
  cidr: 172.16.100.10/24
  primary_ip: 172.16.100.2
- name: Infra  
  cidr: 192.168.10.0/26
  primary_ip: 192.168.10.2
- name: Ert
  cidr: 192.168.20.0/22
  primary_ip: 192.168.20.2
- name: PCF-Tiles
  cidr: 192.168.24.0/22
  primary_ip: 192.168.24.2
- name: Dynamic-Services
  cidr: 192.168.28.0/22
  primary_ip: 192.168.28.2
#- name: IsoZone-01
#  cidr: 192.168.32.0/22
#  primary_ip: 192.168.32.2
# - name: IsoZone-02
#   cidr: 192.168.36.0/22
#   primary_ip: 192.168.36.2


